import { renderTemplate } from "../core/template.js";

export function projectAgents(name: string): string {
  return renderTemplate("project/AGENTS.md.template", { PROJECT_NAME: name });
}

export function contextMap(name: string): string {
  return renderTemplate("project/CONTEXT_MAP.md.template", { PROJECT_NAME: name });
}

export function projectOverview(name: string, repository?: string, projectId?: string): string {
  return renderTemplate("project/PROJECT.md.template", {
    PROJECT_NAME: name,
    PROJECT_ID: projectId ?? "",
    REPOSITORY_SUFFIX: repository ? " for the source repository resolved through `repo/`" : "",
    REPOSITORY_GUIDANCE: repository ? "Use `repo/` as the stable source path. Machine-specific paths belong only in `.local/state.json` and the symlink target." : "No source repository is attached yet.",
  });
}

export const architectureTemplate = renderTemplate("project/ARCHITECTURE.md.template", {});
// Retained only to identify and remove the exact agent file generated by older project layouts.
export const projectContextAgent = renderTemplate("project/PROJECT_CONTEXT_AGENT.md.template", {});
